on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

name: Main Workflow
jobs:
  sonarqube:
    name: Build and analyze on SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'oracle'
          cache: 'maven'
      - name: Install Prerequisites
        run: sudo apt-get update && sudo apt-get install -y unzip wget curl maven
      - name: Cache SonarQube packages
        uses: actions/cache@v4.2.4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Create .env file
        run: |
          echo "POSTGRES_USER=user" >> .env
          echo "POSTGRES_PASSWORD=password" >> .env
          echo "POSTGRES_URL=jdbc:postgresql://localhost:5432/mydb" >> .env
      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.qualitygate.wait=true