CREATE SCHEMA calories;
CREATE TABLE calories.ingredients
(
    id       BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name     TEXT    NOT NULL UNIQUE,
    calories NUMERIC NOT NULL,
    fats     NUMERIC NOT NULL,
    carbs    NUMERIC NOT NULL,
    proteins NUMERIC NOT NULL,
    EAN      VARCHAR(13) UNIQUE
);
CREATE TABLE calories.meals
(
    id   BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL UNIQUE
);
CREATE TABLE calories.meals_ingredients
(
    meal_id       BIGINT NOT NULL,
    ingredient_id BIGINT NOT NULL,
    weight        INT    NOT NULL,
    PRIMARY KEY (meal_id, ingredient_id),
    FOREIGN KEY (meal_id) REFERENCES calories.meals (id),
    FOREIGN KEY (ingredient_id) REFERENCES calories.ingredients (id)
);
CREATE TABLE public.users
(
    id       BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR NOT NULL UNIQUE
);
CREATE TABLE calories.intake_history
(
    id            BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id       BIGINT  NOT NULL,
    date          DATE    NOT NULL,
    calories      NUMERIC NOT NULL,
    protein       NUMERIC NOT NULL,
    fat           NUMERIC NOT NULL,
    carbs         NUMERIC NOT NULL,
    calories_goal INT     NOT NULL,
    protein_goal  INT     NOT NULL,
    fat_goal      INT     NOT NULL,
    carbs_goal    INT     NOT NULL,
    FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE CASCADE
);
CREATE TABLE calories.day
(
    date    DATE PRIMARY KEY,
    user_id BIGINT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE CASCADE
);
CREATE TABLE calories.day_meal
(
    day_date DATE   NOT NULL,
    meal_id  BIGINT NOT NULL,
    weight   INT    NOT NULL,
    meal_type VARCHAR(20) NOT NULL,
    PRIMARY KEY (day_date, meal_id),
    FOREIGN KEY (day_date) REFERENCES calories.day (date) ON DELETE CASCADE,
    FOREIGN KEY (meal_id) REFERENCES calories.meals (id) ON DELETE CASCADE
);