CREATE TABLE calories.ingredients
(
    id       BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name     TEXT        NOT NULL,
    calories NUMERIC     NOT NULL,
    fat      NUMERIC     NOT NULL,
    carbs    NUMERIC     NOT NULL,
    protein  NUMERIC     NOT NULL,
    EAN      VARCHAR(13) NOT NULL
);
CREATE TABLE calories.meals
(
    id   BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL
);
CREATE TABLE calories.meal_ingredients
(
    id            BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    meal_id       BIGINT  NOT NULL,
    ingredient_id BIGINT  NOT NULL,
    amount        NUMERIC NOT NULL,
    FOREIGN KEY (meal_id) REFERENCES calories.meals (id),
    FOREIGN KEY (ingredient_id) REFERENCES calories.ingredients (id)
);
CREATE TABLE public.users
(
    id       BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username TEXT   NOT NULL UNIQUE
);
CREATE TABLE calories.intake_history
(
    id            BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id       BIGINT  NOT NULL,
    date          DATE    NOT NULL,
    calories      NUMERIC NOT NULL,
    protein       NUMERIC NOT NULL,
    fat           NUMERIC NOT NULL,
    carbs         NUMERIC NOT NULL,
    calories_goal INT     NOT NULL,
    protein_goal  INT     NOT NULL,
    fat_goal      INT     NOT NULL,
    carbs_goal    INT     NOT NULL,
    FOREIGN KEY (user_id) REFERENCES public.users (id)
);